spring.application.name=event
spring.data.mongodb.uri=mongodb+srv://azureuser:Shan%251998@eventdb.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
spring.data.mongodb.database=eventdb
server.port=8080
skiddle.api.key=753aa8f35b04d51c2d6589c03f640e15
skiddle.api.url=https://www.skiddle.com/api/v1/events/search/
pixabay.api.key=55128889-b861cd93882b6a21285a1459b

unsplash.api.key=vxInml2QjwLHBJr9-NKju-qcSyOuE7q5vz_21BmbYyQ
unsplash.image.url=https://api.unsplash.com
sentiment.api.key=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
sentiment.api.url=https://router.huggingface.co/hf-inference/models/cardiffnlp/twitter-roberta-base-sentiment-latest
weather.api.key=9a86738447d73424a192439f7095b537