spring.application.name=event
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/eventdb?authSource=admin
server.port=8080
skiddle.api.key=753aa8f35b04d51c2d6589c03f640e15
skiddle.api.url=https://www.skiddle.com/api/v1/events/search/
pixabay.api.key=55128889-b861cd93882b6a21285a1459b
pixabay.image.url=https://pixabay.com/api/
pixabay.video.url=https://pixabay.com/api/videos/